services:

  db:
    image: mariadb:11.4
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - "/back/volume/mariadb:/var/lib/mysql"
    restart: always
    networks:
      - portfolio-network
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress # PLEASE CHANGE_IT_FOR_PRODUCTION
      - MYSQL_DATABASE=wordpress      # PLEASE CHANGE_IT_FOR_PRODUCTION
      - MYSQL_USER=wordpress          # PLEASE CHANGE_IT_FOR_PRODUCTION
      - MYSQL_PASSWORD=wordpress      # PLEASE CHANGE_IT_FOR_PRODUCTION

  wordpress:
    image: wordpress:latest
    volumes:
      - "/back/volume/wordpress:/var/www/html"
    ports:
      - 80:80
    networks:
      - portfolio-network
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db              # PLEASE CHANGE_IT_FOR_PRODUCTION
      - WORDPRESS_DB_USER=wordpress       # PLEASE CHANGE_IT_FOR_PRODUCTION
      - WORDPRESS_DB_PASSWORD=wordpress   # PLEASE CHANGE_IT_FOR_PRODUCTION
      - WORDPRESS_DB_NAME=wordpress       # PLEASE CHANGE_IT_FOR_PRODUCTION

  portfolio-media:
    image: nginx:alpine
    restart: always
    networks:
      - nextjs-network
      - portfolio-network
    volumes:
      - "/back/volume/wordpress/wp-content/uploads:/usr/share/nginx/html/wp-content/uploads:ro"
      - "/back/volume/media/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - wordpress

  cache:
    image: redis:7.4-alpine
    restart: always
    networks:
      - portfolio-network
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "/back/volume/redis:/data"

  portfolio:
    image: ghcr.io/thibault0712/portfolio:latest
    env_file:
      - .env
    networks:
      - portfolio-network
      - nextjs-network
    ports:
      - 81:8080
    environment:
      - WORDPRESS_URL=http://wordpress:80
      - WORDPRESS_GRAPHQL_URL=
      - WORDPRESS_CATEGORY_PROJECTS_ID=3
      - WORDPRESS_CATEGORY_BLOG_ID=4
      - MAX_ARTICLES_PROJECTS=3
      - MAX_ARTICLES_BLOG=3
      - WORDPRESS_REVALIDATE_SECONDS=300
    depends_on:
      - wordpress

networks:

  portfolio-network:
