import type sanitizeHtml from "sanitize-html";

/** `class` est conservé sur ces balises car les blocs Gutenberg s'identifient par leurs classes. */
const TAGS_KEEPING_CLASS = [
    "a",
    "blockquote",
    "code",
    "div",
    "figure",
    "img",
    "li",
    "ol",
    "p",
    "pre",
    "span",
    "table",
    "ul",
] as const;

const allowedAttributes: sanitizeHtml.IOptions["allowedAttributes"] = {
    ...Object.fromEntries(TAGS_KEEPING_CLASS.map((tag) => [tag, ["class"]])),
    a: ["href", "target", "rel", "title", "class"],
    img: ["src", "alt", "width", "height", "srcset", "sizes", "loading", "decoding", "class"],
    iframe: ["src", "title", "allow", "allowfullscreen", "loading", "referrerpolicy"],
    video: ["src", "controls", "poster", "preload", "playsinline", "muted", "loop"],
    source: ["src", "type"],
    td: ["colspan", "rowspan"],
    th: ["colspan", "rowspan", "scope"],
};

export const sanitizeOptions: sanitizeHtml.IOptions = {
    allowedTags: [
        "a",
        "blockquote",
        "br",
        "code",
        "div",
        "em",
        "figure",
        "figcaption",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "hr",
        "iframe",
        "img",
        "li",
        "ol",
        "p",
        "pre",
        "source",
        "span",
        "strong",
        "table",
        "tbody",
        "td",
        "tfoot",
        "th",
        "thead",
        "tr",
        "ul",
        "video",
    ],
    allowedAttributes,
    allowedSchemes: ["http", "https", "mailto", "tel"],
    allowedSchemesByTag: {
        img: ["http", "https"],
        iframe: ["http", "https"],
        video: ["http", "https"],
        source: ["http", "https"],
    },
};
